from .responses import ApiResponse,GenericExceptionResponse
from .staff import CreateStaff,StaffResponse,GiveAdminPermissionParams
from .student import CreateStudent,StudentResponse,StudentCreateParams,DeleteStudentParams,UpdateStudentParams,UpdateStudentSchema,UpdateAddressSchema
from .standard import CreateStandardRequest, CreateStandardQueryParams, StandardResponse,StandardQueryParams
from .govtid import GovtIdSchema,UpdateGovtIdSchema
from .auth import LoginData,TokenData
from .imageUpload import ImageUploadQueryParams
from .attendance import CreateAttendanceRequest,AttendanceResponse,CreateAttendanceQueryParams
from .parent import ParentCreate,ParentResponse,UpdateParentSchema